//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Application.Common;
using MediatR;
using System.Linq;


namespace Application.Features.VehicleDomain.Vehicles_Tests.Queries.GetVehicles_TestsForGrid
{
    
    
    public class GetVehicles_TestsForGridQuery : IRequest<IQueryable<Vehicles_TestGridModel>>
    {
        
        public FilterModel Filter { get; set; }//;
    }
}
