//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Features.VehicleDomain.Vehicles_Tests.Queries.GetVehicles_TestsForGrid
{
    
    
    public class Vehicles_TestGridModel
    {
        
        public int Id { get; set; }//;
        
        public string Name { get; set; }//;
        
        public int Capacity { get; set; }//;
        
        public int VehicleModel_TestId { get; set; }//;
    }
}
