//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Application.Common;
using Application.VehicleDomain;
using MediatR;
using System.Linq;


namespace Application.Features.VehicleDomain.Vehicles_Tests.Queries.GetVehicles_TestsList
{
    
    
    public class GetVehicles_TestsListQueryHandler : IRequestHandler<GetVehicles_TestsListQuery,List<Id_Caption>>
    {
        
        private IVehicles_TestQuery _vehicles_testQuery;
        
        public GetVehicles_TestsListQueryHandler(IVehicles_TestQuery vehicles_testQuery)
        {
            _vehicles_testQuery = vehicles_testQuery ;
        }
        
        public async Task<List<Id_Caption>> Handle(GetVehicles_TestsListQuery request, CancellationToken  cancellationToken)
        {
            throw new NotImplementedException();;
        }
    }
}
