//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Entities
{
    
    
    public class Vehicles_Test
    {
        
        public int Id { get; set; }//;
        
        public string Name { get; set; }//;
        
        public int Capacity { get; set; }//;
        
        public int VehicleModel_TestId { get; set; }//;
        
        public Database.Entities.VehicleModel_Test VehicleModel_Test { get; set; }//;
    }
}
