// <auto-generated />
using System;
using Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeGenerator.Migrations
{
    [DbContext(typeof(CodeGeneratorDbContext))]
    partial class CodeGeneratorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodeGenerator.Data.Entities.Api", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apis");
                });

            modelBuilder.Entity("CodeGenerator.Data.Entities.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApiId")
                        .HasColumnType("int");

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApiId");

                    b.HasIndex("ParentId");

                    b.ToTable("ObjectTypes");
                });

            modelBuilder.Entity("CodeGenerator.Data.Entities.RequestParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApiId")
                        .HasColumnType("int");

                    b.Property<byte?>("AttributeType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Filterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sortable")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApiId");

                    b.ToTable("RequestParameters");
                });

            modelBuilder.Entity("CodeGenerator.Data.Entities.ResponseParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApiId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsList")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObjectTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PrimitiveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApiId");

                    b.HasIndex("ObjectTypeId");

                    b.ToTable("ResponseParameters");
                });

            modelBuilder.Entity("CodeGenerator.Data.Entities.ObjectType", b =>
                {
                    b.HasOne("CodeGenerator.Data.Entities.Api", "Api")
                        .WithMany("ObjectTypes")
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeGenerator.Data.Entities.ObjectType", "Parent")
                        .WithMany("Child")
                        .HasForeignKey("ParentId");

                    b.Navigation("Api");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CodeGenerator.Data.Entities.RequestParameter", b =>
                {
                    b.HasOne("CodeGenerator.Data.Entities.Api", "Api")
                        .WithMany("RequestParameters")
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Api");
                });

            modelBuilder.Entity("CodeGenerator.Data.Entities.ResponseParameter", b =>
                {
                    b.HasOne("CodeGenerator.Data.Entities.Api", "Api")
                        .WithMany("ResponseParameters")
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeGenerator.Data.Entities.ObjectType", "ObjectType")
                        .WithMany()
                        .HasForeignKey("ObjectTypeId");

                    b.Navigation("Api");

                    b.Navigation("ObjectType");
                });

            modelBuilder.Entity("CodeGenerator.Data.Entities.Api", b =>
                {
                    b.Navigation("ObjectTypes");

                    b.Navigation("RequestParameters");

                    b.Navigation("ResponseParameters");
                });

            modelBuilder.Entity("CodeGenerator.Data.Entities.ObjectType", b =>
                {
                    b.Navigation("Child");
                });
#pragma warning restore 612, 618
        }
    }
}
