//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Application.Common;
using MediatR;
using System.Linq;


namespace Application.Features.VehicleDomain.Vehicles_Tests.Commands.EditVehicles_Test
{
    
    
    public class EditVehicles_TestCommand : IRequest
    {
        
        public int Id { get; set; }//;
        
        public string Name { get; set; }//;
        
        public int Capacity { get; set; }//;
        
        public int VehicleModel_TestId { get; set; }//;
    }
}
